fixed modal closing when it wasn't supposed to
FreeCodeCamp-SLC/react-booklist pull request #28
Opened 2022-03-14 23:07 UTC by yankeehotelfoxtrot51

closeModal checks for class 'closeModal'
fixed #26

2022-03-23 01:51 UTC, zorro1rr commented on package.json
> -    "eslint": "^7.24.0",
Can we add this back and run NPM Install

2022-03-23 01:55 UTC, zorro1rr requested changes

2022-03-23 01:55 UTC, zorro1rr commented on src/components/App.jsx
> +          <AuthenticateRoute path={`/lists/:book_id`}>
can we actually make this /book/:book_id?

2022-03-24 17:54 UTC, yankeehotelfoxtrot51 reviewed
made those changes for you - eslint should be back in and the bookpage it should link to books/book_id

2022-03-25 22:21 UTC, zorro1rr approved these changes

2022-03-25 22:21 UTC, merged