Added styled sign-in page
FreeCodeCamp-SLC/react-booklist pull request #8
Opened 2021-02-24 02:04 UTC by klinton24

Added styled sign-in page.

2021-02-24 03:28 UTC, mikelnorth requested changes

2021-02-24 03:28 UTC, mikelnorth commented on package.json
> +    "styled-components": "^5.2.1",
So we will actually be using post css instead of styled components since thats what tailwindcss seems to go that route.

@briancbarrow is that correct?

2021-02-24 03:28 UTC, mikelnorth commented on src/components/SignIn/styles.js
> +import styled from "styled-components";
@briancbarrow @AlexanderPuhl With using tailwindcss do we want to use styled components. I would like to use 1 approach for styling our application.

Does tailwindcss work with styledcomponents

From what I see we would have to use a specific styled-components-tailwind rather than the one already installed

https://www.ibrahima-ndaw.com/blog/how-to-use-tailwind-styled-components/

2021-02-24 03:28 UTC, mikelnorth commented on src/components/SignIn/styles.js
> +    margin: 0px !important;
Do we need the !important here? If so can we instead try to use specificity instead?

2021-02-24 03:28 UTC, mikelnorth commented on src/components/SignIn/styles.js
> +    &:focus {
For accessibility reasons we need some sort of indicator that a actionable field is in focus. We don't need to use the default but we should not just remove it

2021-02-24 03:29 UTC, mikelnorth commented
Hey Awesome stuff here! a few comments, its looking good!

2021-02-24 03:41 UTC, mikelnorth requested changes

2021-02-24 03:41 UTC, mikelnorth commented on src/components/SignIn/SignIn.css
> +button:focus {
For accessibility we should not remove a focus state. See my comment bellow for more

2021-03-03 01:37 UTC, AlexanderPuhl commented on src/components/SignIn/styles.js
> +    margin: 0px !important;
I agree w/ removing the important if possible.

2021-03-03 01:49 UTC, briancbarrow commented
Closing because we're going with Tailwind instead of styled components

2021-03-03 01:49 UTC, closed without merging